"""Controlled vocabularies.

Every enum keeps an ``UNKNOWN`` member. ``UNKNOWN`` is a positive statement
("the source does not support a classification"), never a negative claim.
"""

from __future__ import annotations

from enum import StrEnum


class Authority(StrEnum):
    CNMV = "CNMV"
    AEBOE = "AEBOE"


class DocumentType(StrEnum):
    # CNMV surface
    CNMV_REGISTER_PAGE = "CNMV_REGISTER_PAGE"
    CNMV_REGISTER_SNAPSHOT = "CNMV_REGISTER_SNAPSHOT"
    CNMV_RESOLUTION_PDF = "CNMV_RESOLUTION_PDF"
    CNMV_APPEAL_NOTICE = "CNMV_APPEAL_NOTICE"
    CNMV_JUDICIAL_RESULT = "CNMV_JUDICIAL_RESULT"
    # BOE surface
    BOE_SUMARIO = "BOE_SUMARIO"
    BOE_XML = "BOE_XML"
    BOE_HTML = "BOE_HTML"
    BOE_PDF = "BOE_PDF"
    # other
    OTHER_OFFICIAL_DOCUMENT = "OTHER_OFFICIAL_DOCUMENT"


class DocumentRole(StrEnum):
    """The semantic role a document plays in the ledger.

    A BOE publication resolution is NOT the full sanctioning decision.
    """

    REGISTER_LISTING = "REGISTER_LISTING"
    PUBLICATION_RESOLUTION = "PUBLICATION_RESOLUTION"
    FULL_RESOLUTION = "FULL_RESOLUTION"
    CORRECTION = "CORRECTION"
    APPEAL_NOTICE = "APPEAL_NOTICE"
    JUDICIAL_RESULT = "JUDICIAL_RESULT"
    UNCLASSIFIED = "UNCLASSIFIED"


class RespondentType(StrEnum):
    LEGAL_PERSON = "LEGAL_PERSON"
    NATURAL_PERSON = "NATURAL_PERSON"
    ANONYMIZED_PERSON = "ANONYMIZED_PERSON"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"


class SanctionType(StrEnum):
    MONETARY_FINE = "MONETARY_FINE"
    DISGORGEMENT = "DISGORGEMENT"
    PUBLIC_REPRIMAND = "PUBLIC_REPRIMAND"
    SUSPENSION = "SUSPENSION"
    DISQUALIFICATION = "DISQUALIFICATION"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"


class Severity(StrEnum):
    VERY_SERIOUS = "VERY_SERIOUS"  # muy grave
    SERIOUS = "SERIOUS"  # grave
    MINOR = "MINOR"  # leve — out of register scope, kept for completeness
    UNKNOWN = "UNKNOWN"


class RuleResolutionStatus(StrEnum):
    VALID_FOR_CONDUCT = "VALID_FOR_CONDUCT"
    UNRESOLVED_RULE_VERSION = "UNRESOLVED_RULE_VERSION"
    AMBIGUOUS_VERSION = "AMBIGUOUS_VERSION"
    NO_RULE_DEFINED = "NO_RULE_DEFINED"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class EventType(StrEnum):
    RESOLUTION = "RESOLUTION"
    ADMINISTRATIVE_APPEAL = "ADMINISTRATIVE_APPEAL"
    ADMINISTRATIVE_FINALITY = "ADMINISTRATIVE_FINALITY"
    BOE_PUBLICATION = "BOE_PUBLICATION"
    BOE_CORRECTION = "BOE_CORRECTION"
    JUDICIAL_APPEAL_FILED = "JUDICIAL_APPEAL_FILED"
    JUDGMENT = "JUDGMENT"
    ANNULMENT = "ANNULMENT"
    PARTIAL_ANNULMENT = "PARTIAL_ANNULMENT"
    MODIFICATION = "MODIFICATION"
    OTHER = "OTHER"


class RelationshipType(StrEnum):
    CORRECTS = "CORRECTS"
    SUPERSEDES = "SUPERSEDES"
    RELATES_TO = "RELATES_TO"
    PUBLISHES = "PUBLISHES"
    REPORTS_APPEAL_OF = "REPORTS_APPEAL_OF"
    REPORTS_JUDGMENT_OF = "REPORTS_JUDGMENT_OF"


class ExtractionMethod(StrEnum):
    DIRECT = "DIRECT"
    NORMALIZED = "NORMALIZED"
    DERIVED = "DERIVED"
    MANUALLY_REVIEWED = "MANUALLY_REVIEWED"


class ConfidenceType(StrEnum):
    """Not a probabilistic score — a provenance class."""

    DIRECT = "DIRECT"
    NORMALIZED = "NORMALIZED"
    DERIVED = "DERIVED"
    MANUALLY_REVIEWED = "MANUALLY_REVIEWED"


class ObservedState(StrEnum):
    """Projected, never authoritative. Derived from the event log only."""

    OBSERVED_FINAL = "OBSERVED_FINAL"
    OBSERVED_APPEALED = "OBSERVED_APPEALED"
    OBSERVED_ANNULLED = "OBSERVED_ANNULLED"
    OBSERVED_PARTIALLY_ANNULLED = "OBSERVED_PARTIALLY_ANNULLED"
    OBSERVED_CONFIRMED = "OBSERVED_CONFIRMED"
    OBSERVED_MODIFIED = "OBSERVED_MODIFIED"
    UNKNOWN = "UNKNOWN"


class CoverageStatus(StrEnum):
    UNVERIFIED = "UNVERIFIED"
    OBSERVED_SNAPSHOT = "OBSERVED_SNAPSHOT"
    REPRODUCIBLY_ENUMERATED = "REPRODUCIBLY_ENUMERATED"
    VERIFIED = "VERIFIED"
    PARTIAL = "PARTIAL"


class ConductCode(StrEnum):
    MARKET_ABUSE__INSIDER_DEALING = "MARKET_ABUSE.INSIDER_DEALING"
    MARKET_ABUSE__UNLAWFUL_DISCLOSURE = "MARKET_ABUSE.UNLAWFUL_DISCLOSURE"
    MARKET_ABUSE__MARKET_MANIPULATION = "MARKET_ABUSE.MARKET_MANIPULATION"
    DISCLOSURE__PERIODIC_REPORTING = "DISCLOSURE.PERIODIC_REPORTING"
    DISCLOSURE__INSIDE_INFORMATION = "DISCLOSURE.INSIDE_INFORMATION"
    DISCLOSURE__SIGNIFICANT_HOLDINGS = "DISCLOSURE.SIGNIFICANT_HOLDINGS"
    DISCLOSURE__GOVERNANCE = "DISCLOSURE.GOVERNANCE"
    INVESTMENT_SERVICES__CONDUCT_OF_BUSINESS = "INVESTMENT_SERVICES.CONDUCT_OF_BUSINESS"
    INVESTMENT_SERVICES__CLIENT_ASSETS = "INVESTMENT_SERVICES.CLIENT_ASSETS"
    INVESTMENT_SERVICES__BEST_EXECUTION = "INVESTMENT_SERVICES.BEST_EXECUTION"
    INVESTMENT_SERVICES__ORGANISATIONAL_REQUIREMENTS = (
        "INVESTMENT_SERVICES.ORGANISATIONAL_REQUIREMENTS"
    )
    COLLECTIVE_INVESTMENT__INVESTMENT_POLICY = "COLLECTIVE_INVESTMENT.INVESTMENT_POLICY"
    COLLECTIVE_INVESTMENT__VALUATION = "COLLECTIVE_INVESTMENT.VALUATION"
    COLLECTIVE_INVESTMENT__DISCLOSURE = "COLLECTIVE_INVESTMENT.DISCLOSURE"
    COLLECTIVE_INVESTMENT__RISK_MANAGEMENT = "COLLECTIVE_INVESTMENT.RISK_MANAGEMENT"
    SHORT_SELLING = "SHORT_SELLING"
    TAKEOVERS = "TAKEOVERS"
    PRUDENTIAL = "PRUDENTIAL"
    AML = "AML"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"
